function LinkAxes(option)

% LINKAXES - Link axes after plotting.
% LinkAxes
% LinkAxes('time')
% LinkAxes('freq')
%
% Links axes generated by "PlotSignalGroup", "PlotDataset", 
% and related functions.  Optionally, specify 'time' to link 
% the "Timeseries" plots only, or 'freq' to link the "Spectrum" 
% plots only. 
%
% P.G. Bonanni
% 5/27/20

% Copyright (c) 2024  Pierino G. Bonanni
% Distributed under GNU General Public License v2.0.


if nargin == 0
  option = [];
end

% Link time axes
h = findobj('Tag','Timeseries');
if length(h) > 1 && (isempty(option) || strncmpi(option,'time',4))
  xlim = get(h,'XLim');
  xlim = cat(1,xlim{:});
  xlim = [min(xlim(:,1)),max(xlim(:,2))];
  linkaxes(h,'x')
  set(h,'XLim',xlim)
end

% Link frequency axes
h = findobj('Tag','Spectrum');
if length(h) > 1  && (isempty(option) || strncmpi(option,'freq',4))
  xlim = get(h,'XLim');
  xlim = cat(1,xlim{:});
  xlim = [min(xlim(:,1)),max(xlim(:,2))];
  linkaxes(h,'x')
  set(h,'XLim',xlim)
end
