function UnlinkAxes(option)

% UNLINKAXES - Un-link axes after plotting.
% UnlinkAxes
% UnlinkAxes('time')
% UnlinkAxes('freq')
%
% Un-links axes generated by "PlotSignalGroup", "PlotDataset", 
% and related functions.  Optionally, specify 'time' to un-link 
% the "Timeseries" plots while keeping "Spectrum" plots linked, 
% or 'freq' to perform the vice-versa option. 
%
% P.G. Bonanni
% 3/19/18

% Copyright (c) 2024  Pierino G. Bonanni
% Distributed under GNU General Public License v2.0.


if nargin == 0
  option = [];
end

% Unlink time axes
h = findobj('Tag','Timeseries');
if ~isempty(h) && (isempty(option) || strncmpi(option,'time',4))
  linkaxes(h,'off')
end

% Un-link frequency axes
h = findobj('Tag','Spectrum');
if ~isempty(h) && (isempty(option) || strncmpi(option,'freq',4))
  linkaxes(h,'off')
end
